spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/bookAdminApp
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.MariaDB53Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true